# -*- coding: utf-8 -*-
"""Factive minds Exercise 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tGlMggB5vZ03t1zyTR91XS4YmXGPJweT

### 1. How to check if a string contains only numbers in Python
"""

ini_string1 = '1234556'
ini_string2 = 'ab123bc'
 
# printing initial string
print ("Initial Strings : ", ini_string1, ini_string2)
 
# Using isdigit()
if ini_string1.isdigit():
    print ("String1 contains all numbers")
else:
    print ("String1 doesn't contains all numbers")
     
if ini_string2.isdigit():
    print ("String2 contains all numbers")
else:
    print ("String2 doesn't contains all numbers")

"""### 2. How to find duplicate characters in a String? """

string = input("Enter the string: ")

for i in range(0,len(string)):
    count = 1
    for j in range(i+1,len(string)):
        if (string[i] == string[j] and string[i]!=''):
            count = count + 1
            string = string[:j] + '0' + string[j+1:] 
            
    if (count>1 and string[i]!='0'):
        print(string[i])

"""### 3. How to count a number of vowels and consonants in a given String?"""

string = input("Enter the string: ")

vowels=0
consonants=0

for i in string:
    if (i=='A' or i=='E' or i=='I' or i=='O' or i=='U'
       or i=='a' or i=='e' or i=='i' or i=='o' or i=='u'):
        vowels=vowels+1
    else:
        consonants=consonants+1
        
print("The number of consonants are:",consonants) 
print("The number of vowels are:",vowels)

"""### 4. How to count the occurrence of a given character in String? """

str = input("Enter the string: ")
i = input("Enter the character: ")

x=str.lower()
count = x.count(i)

print("The occurence of ",i," in ",str,":",count)

str = input("Enter the string: ")
i = input("Enter the character: ")

import re
count=len(re.findall(i,str))

print("The occurence of ",i," in ",str,":",count)

"""### 5.	How to find all permutations of String? """

# Python code to demonstrate
# to find all permutation of
# a given string
 
from itertools import permutations
 
# Initialising string
ini_str = "abc"
 
# Printing initial string
print("Initial string", ini_str)
 
# Finding all permutation
permutation = [''.join(p) for p in permutations(ini_str)]
# Printing result
print("Resultant List", str(permutation))

"""### 6.	How to find & count any given pattern from a text, 
e.g. ‘EDUCATION’, find number of ‘CAT' occurrence in the text?

"""



"""### 7.	How to remove duplicates from an array in place?"""

import numpy as np
list = [1,1,1,2,3,3,4,5,5,6,6]
final_list = np.unique(list).tolist()
print(final_list)

"""### Using Pandas"""

import pandas as pd
list = [1,1,1,2,3,3,4,5,5,6,6]
final_list = pd.unique(list).tolist()
print(final_list)

"""### 8.	How to reverse a String?"""

str = input("Enter the string: ")
print(str[::-1])

str = input("Enter the string: ")
print("".join(reversed(str)))

"""### 9.	How to find the highest repeating word from a given file?"""

file=open("/content/nj.txt")
freq_word=""
frequency=0
words=[]

for line in file:
    line_word=line.lower().replace(',','').replace('.','').replace('?','').split(" ")
    for x in line_word:
        words.append(x)

for i in range(0,len(words)):
    count=1
    for j in range(i+1,len(words)):
        if(words[i]==words[j]):
            count=count+1
            
    if count>frequency :
        frequency=count
        freq_word=words[i]
        
print("Highest repeated word: " + freq_word)
print("Frequency",frequency)
file.close()

"""### 10.	How to check if the given number is a prime number?"""

n = int(input("Enter the number:"))

if n%2 != 0:
    print(n,"is a prime number")
else:
    print(n,"is not a prime number")

n = int(input("Enter the number:"))

if n>1 :
    
    for i in range(2, int(n/2)+1):
        if n%i == 0:
            print(n, "not a prime")
            break
    else:
        print(n, "is prime")      
else:
    print(n,"is not a prime number")



"""### 11.	How do you find all prime factors of a given number?"""

# python program to print prime factors
 
import math
def primefactors(n):
   #even number divisible
   while n % 2 == 0:
      print (2),
      n = n / 2
    
   #n became odd
   for i in range(3,int(math.sqrt(n))+1,2):
     
      while (n % i == 0):
         print (i)
         n = n / i
    
   if n > 2:
      print (n)
 
n = int(input("Enter the number for calculating the prime factors :\n"))
primefactors(n)

"""### 12.	Write a Program to transpose a Matrix?"""

x=[[1,2],[4,6],[8,9]]
result=[[0,0,0],[0,0,0]]

for i in range(len(x)):
    for j in range(len(x[0])):
        result[j][i] = x[i][j]    
        
print(result)

"""### 13.	Write a Program to add or subtract two Matrices?"""

import numpy as np

x1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
x2 = np.array([[11,12,13],[14,15,16],[17,18,19]])

print(np.add(x1,x2))
print(np.subtract(x2,x1))

"""### 14.	How to implement the Bubble Sort algorithm?"""

list = [21,6,9,33,3]

n=len(list)
 
for i in range (n-1):
    for j in range(0,n-i-1):
        if list[j]>list[j+1]:
            temp=list[j+1]
            list[j+1]=list[j]
            list[j]=temp
            
print(list)

"""### 15.	Find the words and its count for a given text file?"""

file=open("/content/nj.txt")
data=file.read()
words=data.split()

print("Number of words in a text file:",len(words))
print("Words in a text file: \n",words)

